use_frameworks!

platform :ios, '9.0'

target 'SSExtension_Example' do
  pod 'SSExtension', :path => '../'

  target 'SSExtension_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
